#!/bin/bash
# Dispatcher script to start/stop captive portal

IFACE="$1"
STATUS="$2"

HOTSPOT_NAME="Hotspot"

if [ "$STATUS" = "up" ]; then
    ACTIVE_CON=$(nmcli -t -f NAME,DEVICE connection show --active | grep ":$IFACE$" | cut -d: -f1)
    if [ "$ACTIVE_CON" = "$HOTSPOT_NAME" ]; then
        systemctl start captive-portal.service
    else
        systemctl stop captive-portal.service
    fi
fi

if [ "$STATUS" = "down" ]; then
    # If hotspot goes down, stop the service
    systemctl stop captive-portal.service
fi
